# Trigger re-index for GitHub Actions
name: Run Stock Update

on:
  workflow_dispatch:

jobs:
  update-stock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stock update script
        env:
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
          TARGET_LOCATION_ID: ${{ secrets.TARGET_LOCATION_ID }}
          FLAM_USERNAME: ${{ secrets.FLAM_USERNAME }}
          FLAM_PASSWORD: ${{ secrets.FLAM_PASSWORD }}
          FLAM_URL: ${{ secrets.FLAM_URL }}
        run: python update_all_stock_github.py 